name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23likdP92i3c8Xka2z"
GITHUB_OWNER = "LIU666-ai"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav.yongqiang.com/api/auth"
NEXT_PUBLIC_API_URL="https://nav.yongqiang.com"

